rasterizer:
  command: phantomjs   # phantomjs executable
  port: 4001           # internal service port. No need to allow inbound or outbound access to this port
  path: '/tmp/'        # where the screenshot files are stored
  layout: 'Letter'
  orientation: 'portrait'
cache:
  lifetime: 60000      # one minute, set to 0 for no cache
server:
  port: 4000           # main service port
  useCors: false       # enable CORS support
